# configs/system_config.yml
minio:
  endpoint: "127.0.0.1:9000"
  access_key: "admin"
  secret_key: "SuperSecretPassword123"
  bucket_name: "amazonreviews"
  secure: false

postgres:
  host: "localhost"
  port: 5432
  database: "postgres"
  user: "postgres"
  password: "admin"

qdrant:
  url: "https://f0357a9b-4850-457e-aa42-150d5ef634c1.eu-west-2-0.aws.cloud.qdrant.io"
  api_key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.WVIytk5sCDLSXrKfVZtoa5Z_LtkwBlTYVLAGkT_aZjA"
  prefer_grpc: false
  timeout: 60     # global HTTP timeout (seconds)
  port: null      # avoid appending :6333 to a Cloud URL
